on:
  push:
    #branches:
    #  - main
    tags:
      - "v*"

name: Release policy

jobs:
  release:
    uses: kubewarden/github-actions/.github/workflows/reusable-release-policy-go.yml@v3.1.18
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/kubewarden-policy/k8sblocklatesttag #FIXME
